### ISSUE TITLE
no albums are displayed

### ISSUE THREAD

**Issue by Shootgun13** [broman-pl/plugin.image.dsphoto#1]
Hello,
I installed the plugin on kodi krypton, I added. htaccess on the syno (dsm 6.1). The plugin is properly configured but in the kodi logs I find this:

```
17:42:49.212 T: 1273291760 WARNING: CreateLoader - unsupported protocol (plugin) in plugin: //plugin. image. ds-photo/? action=albums&sid=mki559u42hbloa0p6l5n1mrsh6
17:42:53.984 T: 1234064368 WARNING: CreateLoader - unsupported protocol (plugin) in plugin: //plugin. image. ds-photo/. ds-photo/
```

**Comment by broman-pl** [comment]
Please set your KODI into debug mode and send those logs? This error about unsupported plugin protocol is something different and doesn't affect functionality
